services:
  proxy:
    image: nginx
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    networks:
      - super

  backend:
    depends_on:
      - sqlDb
    build:
      context: backend
      target: builder
    environment:
      - DOCKER=true
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    networks:
      - super

  sqlDb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - ${DB_PORT}:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASS}
      - MSSQL_PID=${DB_VERSION}
    networks:
      - super

networks:
  super:
